### ISSUE TITLE
How to use HTTP proxy with SecretManagerServiceClient Object?

### ISSUE THREAD

**Issue by waytoalpit** [googleapis/java-secretmanager#118]
How to use HTTP proxy with SecretManagerServiceClient Object?

Could not found any method to set the proxy in SecretManagerServiceClient instance.
Please provide sample example if possible.

More context: We are trying to use SecretManagerServiceClient from on-prem hosts which does not allow outbound connections without proxy. I have working proxy with required access. If i simply allow proxy for all non-internal requests, it works perfectly fine.
But i don't want to turn on proxy for all other requests type, just want to enable for GCP SecretManager service.
How can i set the proxy to SecretManagerServiceClient instance in Java/Scala?

**Comment by sethvargo** [comment]
Hi @waytoalpit 

You can learn more about using proxies in the parent java repository readme: https://github.com/googleapis/google-cloud-java#using-a-proxy

**Comment by danoscarmike** [comment]
@waytoalpit I think the linked doc should do the trick for you so closing this issue now. Thanks for reaching out.

**Comment by waytoalpit** [comment]
> @waytoalpit I think the linked doc should do the trick for you so closing this issue now. Thanks for reaching out.

Hi Team,
I already read all the documents. I need to set proxy and auth to SecretManagerServiceClient instance level not at global/OS level.

I don't see any methods where can i either set proxy or HttpTransport to do so.

For example: 
1. How can i get HttpClient from SecretManagerServiceClient so i can set the proxy or auth?
2. Or something like -> public Builder(HttpTransport var1, JsonFactory var2, HttpRequestInitializer var3), where i can create NetHttpTransport with proxy details.

Please let me know if my question is still not clear.

**Comment by waytoalpit** [comment]
> Hi @waytoalpit
> 
> You can learn more about using proxies in the parent java repository readme: https://github.com/googleapis/google-cloud-java#using-a-proxy

Hi Team,
I already read all the documents. I need to set proxy and auth to SecretManagerServiceClient instance level not at global/OS level.

I don't see any methods where can i either set proxy or HttpTransport to do so.

For example:

How can i get HttpClient from SecretManagerServiceClient so i can set the proxy or auth?
Or something like -> public Builder(HttpTransport var1, JsonFactory var2, HttpRequestInitializer var3), where i can create NetHttpTransport with proxy details.
Please let me know if my question is still not clear.

**Comment by chingor13** [comment]
For providing an `HttpTransport` with proxy configuration for the authentication credentials, you can provide a `HttpTransportFactory` to the [`GoogleCredentials.getApplicationDefault(HttpTransportFactory)`](https://googleapis.dev/java/google-auth-library/latest/com/google/auth/oauth2/GoogleCredentials.html#getApplicationDefault-com.google.auth.http.HttpTransportFactory-) then provide those credentials to your SecretManagerServiceSettings (via a FixedCredentialsProvider).

**Comment by waytoalpit** [comment]
> HttpTransportFactory

Thanks chingor13.
I tried below example but still did not work. I believe another thing i am missing is how to provide **authenticator** for proxy. My proxy does require username and password to get the access. I am using service account json key for client credentials. Hence basically i need to assemble all three  to SecretManagerServiceClient -
1) proxy
2) authenticator for proxy(basically username and password)
3) Service account key

== code sample (scala, similar to java) ==
```
....    
    val transport: NetHttpTransport.Builder = new NetHttpTransport.Builder()
      .trustCertificates(GoogleUtils.getCertificateTrustStore)
    val proxiedTransport: NetHttpTransport = transport.setProxy(proxy).build()

    val credentials = GoogleCredentials.fromStream(new FileInputStream(gcpServiceAccountKey),
      getHttpTransportFactory(proxiedTransport)).createScoped(ComputeScopes.all()).toBuilder.build()

    val settings = SecretManagerServiceSettings.newBuilder
      .setCredentialsProvider(FixedCredentialsProvider.create(credentials)).build
    val secretManagerServiceClient = SecretManagerServiceClient.create(settings)
.....

def getHttpTransportFactory(netHttpTransport: NetHttpTransport): HttpTransportFactory = {
    new HttpTransportFactory() {
      override def create: HttpTransport = netHttpTransport
    }
  }
```

gcpServiceAccountKey -> Service account Key Json file

Above code sample does not work and result in below error. 
`error:io.grpc.StatusRuntimeException: UNAVAILABLE: io exception\nChannel Pipeline: [HttpClientCodec#0, HttpProxyHandler#0, ProtocolNegotiators$ProxyProtocolNegotiationHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]']`

Note: I already tested client working fine by enabling proxy at JVM level. So the problem could be the way i am setting proxy with SecretManagerServiceClient.
As said, i may also require to set authenticator for proxy. Please let me know accordingly.

**Comment by waytoalpit** [comment]
> For providing an `HttpTransport` with proxy configuration for the authentication credentials, you can provide a `HttpTransportFactory` to the [`GoogleCredentials.getApplicationDefault(HttpTransportFactory)`](https://googleapis.dev/java/google-auth-library/latest/com/google/auth/oauth2/GoogleCredentials.html#getApplicationDefault-com.google.auth.http.HttpTransportFactory-) then provide those credentials to your SecretManagerServiceSettings (via a FixedCredentialsProvider).

Where are we setting application credential then? I have different application and proxy credentials? How to set all of them to SecretManagerServiceClient instance?
Pls guide.

**Comment by waytoalpit** [comment]
Issue resolved in https://github.com/googleapis/java-secretmanager/issues/119
