### ISSUE TITLE
error:io.grpc.StatusRuntimeException: UNAVAILABLE: io exception\nChannel Pipeline: [HttpClientCodec#0, HttpProxyHandler#0, ProtocolNegotiators$ProxyProtocolNegotiationHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]']

### ISSUE THREAD

**Issue by waytoalpit** [googleapis/java-secretmanager#119]
In continuation to issue: https://github.com/googleapis/java-secretmanager/issues/118 which got closed, opening a new ticket to setup proxy server with authentication. 

My proxy does require username and password to get the access. I am also using service account json key for client credentials. Hence basically i need to assemble all three to SecretManagerServiceClient -

1. proxy
2. authenticator for proxy(basically username and password)
3. Service account key

== code sample (scala, similar to java) ==

```
....    
val proxyHostDetails = new HttpHost(httpProxyHost, httpProxyPort)
val proxyRoutePlanner = new DefaultProxyRoutePlanner(proxyHostDetails);

val credentialsProvider = new BasicCredentialsProvider
credentialsProvider.setCredentials(
  new AuthScope(proxyHostDetails.getHostName, proxyHostDetails.getPort),
  new UsernamePasswordCredentials(
    proxySecrets("username"), proxySecrets("password")
  )
)

val mHttpClient = ApacheHttpTransport.newDefaultHttpClientBuilder
  .setRoutePlanner(proxyRoutePlanner)
  .setRetryHandler(new DefaultHttpRequestRetryHandler)
  .setProxyAuthenticationStrategy(ProxyAuthenticationStrategy.INSTANCE)
  .setDefaultCredentialsProvider(credentialsProvider)
  .build()

val mHttpTransport = new ApacheHttpTransport(mHttpClient)
val httpTransportFactory = getHttpTransportFactory(mHttpTransport)
val testHttpTransport = httpTransportFactory.create()

val credentials = GoogleCredentials.fromStream(new FileInputStream(gcpServiceAccountKey),
  httpTransportFactory).createScoped(ComputeScopes.all())

val settings = SecretManagerServiceSettings.newBuilder
  .setCredentialsProvider(FixedCredentialsProvider.create(credentials)).build
SecretManagerServiceClient.create(settings)
.....

def getHttpTransportFactory(httpTransport: ApacheHttpTransport): HttpTransportFactory = {
    new HttpTransportFactory() {
      override def create: HttpTransport = httpTransport
    }
  }
```
gcpServiceAccountKey -> Service account Key Json file

Above code sample does not work and result in below error.
error:io.grpc.StatusRuntimeException: UNAVAILABLE: io exception\nChannel Pipeline: [HttpClientCodec#0, HttpProxyHandler#0, ProtocolNegotiators$ProxyProtocolNegotiationHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]']

Note: I already tested working client successfully by enabling proxy at JVM level. So the problem could be the way i am setting up proxy and auth with SecretManagerServiceClient.
**My client credential is different than proxy server credentials.**

Please guide accordingly.

**Comment by waytoalpit** [comment]
I am getting similar issues like below ticket related to grpc 

https://github.com/googleapis/java-dialogflow/issues/21
https://github.com/grpc/grpc-java/issues/6118

Try changing grpc versions but could not work.
Please take a look

**Comment by waytoalpit** [comment]
Can someone pls take a look as it feels to be a grpc issue/bug?

**Comment by waytoalpit** [comment]
As per proxy logs, it's resulting in 407.
Seems above code is not using or able to apply proxy auth.

what's the right way to set proxy credentials?

**Comment by chingor13** [comment]
There are 2 separate transports for the credentials (which uses HTTP 1.1) and the actual service (which uses gRPC - protobuf over HTTP2). If you require a non-global proxy, you will need to configure each connection to setup a proxy.

From #118, it looks like you did figure out how to get the proxy working for the credentials instance.

For the gRPC connection, you will need to supply a `ProxyDetector` to the `ManagedChannelBuilder`. To do that for SecretManager, try will want to do something like:
```java
public SecretManagerService getService() {
  TransportChannelProvider transportChannelProvider =
      SecretManagerServiceStubSettings.defaultGrpcTransportProviderBuilder()
          .setChannelConfigurator(
              new ApiFunction<ManagedChannelBuilder, ManagedChannelBuilder>() {
                @Override
                public ManagedChannelBuilder apply(ManagedChannelBuilder managedChannelBuilder) {
                  return managedChannelBuilder.proxyDetector(
                      new ProxyDetector() {
                        @Nullable
                        @Override
                        public ProxiedSocketAddress proxyFor(SocketAddress socketAddress)
                            throws IOException {
                          return HttpConnectProxiedSocketAddress.newBuilder()
                              .setUsername(PROXY_USERNAME)
                              .setPassword(PROXY_PASSWORD)
                              .setProxyAddress(new InetSocketAddress(PROXY_HOST, PROXY_PORT))
                              // TODO: handle better
                              .setTargetAddress((InetSocketAddress) socketAddress)
                              .build();
                        }
                      });
                }
              })
          .build();
  SecretManagerServiceSettings secretManagerServiceSettings =
      SecretManagerServiceSettings.newBuilder()
          .setTransportChannelProvider(transportChannelProvider)
          .setCredentialsProvider(FixedCredentialsProvider.create(googleCredentials))
          .build();
  return SecretManagerServiceClient.create(secretManagerServiceSettings);
}
```

**Comment by waytoalpit** [comment]
Thanks chingor13 for clarifying the solution and code snippet.
It worked like a charm.

Wondering do we expect to have a higher level abstract method/impl to do the same?
