### ISSUE TITLE
SecretManager- Appending a new label removes existing labels on update secret

### ISSUE THREAD

**Issue by waytoalpit** [googleapis/java-secretmanager#123]
Issue: SecretManager 1.0.1 Java API removes existing labels(with different keys) on adding a new label. 
However, Gcloud CLI works as expected.
I need to know whether it's a bug or something i am missing.

I am following the steps as per the documentation:
https://cloud.google.com/secret-manager/docs/managing-secrets

Gcloud CLI:
```
$ gcloud secrets update my-secret --update-labels=foo=bar
Updated secret [my-secret].
$ gcloud secrets describe my-secret
createTime: '2020-04-14T21:59:35.353033Z'
labels:
  foo: bar
name: projects/XXXXXXXXX/secrets/my-secret
replication:
  automatic: {}

$ gcloud secrets update my-secret --update-labels=foo1=bar
Updated secret [my-secret].
$ gcloud secrets describe my-secret
createTime: '2020-04-14T21:59:35.353033Z'
labels:
  foo: bar
  foo1: bar
name: projects/XXXXXXXXX/secrets/my-secret
replication:
  automatic: {}
```

Conclusion: Gcloud CLI appends labels without removing existing labels.

Scala/Java API:
```
val client = SecretManagerServiceClient.create
        try { // Build the name.
          val secretName = SecretName.of("XXXXXXXXXXX", "my-secret")
          // Build the updated secret.
          val secret = Secret
            .newBuilder
            .setName(secretName.toString)
            .putLabels("foo", "bar")
            .build
          // Build the field mask.
          val fieldMask = FieldMaskUtil.fromString("labels")
          val request = UpdateSecretRequest.newBuilder
            .setSecret(secret)
            .setUpdateMask(fieldMask)
            .build

          // Create the secret.
          val updatedSecret = client.updateSecret(request)
          System.out.printf("Updated secret %s\n", updatedSecret.getName)
        } finally if (client != null) client.close()

```

Running above java code every time with unique keys, removes the previous labels with different keys.

Please validate this.

**Comment by tam7t** [comment]
When you issue an `UpdateSecret` request with the `labels` fieldmask you are telling the API that you want to make the new values overwrite the existing labels.

If you would like to append labels you will need to first `GetSecret` to get the current values, mutate your labels, and then issue the `UpdateSecret` with the new labels map.

**Comment by waytoalpit** [comment]
Thanks Tommy for updating the detatails.

Wondering why it work differently with CLI, as mentioned in the above example?
Does CLI involve customized behavior?

**Comment by tam7t** [comment]
Yeah gcloud has some helpers and doesn't directly match the underlying API - for example it provides no way to set all labels in a single command, you have to use the `--clear-labels` and then the `--update-labels`.

You can use the `--log-http` flag with gcloud to see how the commands translate to API calls.

**Comment by waytoalpit** [comment]
Thanks Tommy for the clarification. Appreciate it.

**Comment by danoscarmike** [comment]
Thanks @tam7t. 

@waytoalpit Thanks for reaching out. Closing for now. Let us know if you need anything else.
