### ISSUE TITLE
Slim variant, purely for accessing secrets

### ISSUE THREAD

**Issue by aSemy** [googleapis/java-secretmanager#450]
#### What the problem is

I've got a Google Cloud Function running (Kotlin, Gradle) into which I'd like to inject some api keys. It's a tiny project, just a few .kt files + dependencies. The documentation tells me the preferred way of injecting secrets is with java-secretmanager. However I'm not really satisfied with this. The dependency increases the size of my jar from ~15MB to ~30MB, and when deployed response time decreases.

#### Alternatives considered

I've tried reducing the size of the jar using shadowJar's `minimize()` and `mergeServiceFiles()` in various combinations, but then I get errors that 'io.grpc.netty' is missing. I've tried playing whack-a-mole with trying to find the right mix of dependencies, but I couldn't get it working.

I've tried setting manually fetching the secrets over the REST API, but I'm not able to get authenticated while inside the Cloud Function. The documentation doesn't make authenticating in this situation clear.

#### Proposed solution

I can see that most of the code is generated. Could you produce a stripped down variant just with the `https://secretmanager.googleapis.com/v1/{name=projects/*/secrets/*/versions/*}:access` endpoint? Purely for perfomant fetching of secrets?

#### Alternatives:

An alternative to this would be a guide on how to use the Secrets REST API for Cloud Functions.

Because this is a really small project, I'd really like a small solution for fetching secrets in Java. Maybe there's another option?

---

Additionally, when it is running and installed, and I increase the available memory and accept the slower response time, then I get warnings in the log:

```
Failed to find a usable hardware address from the network interfaces; using random bytes: ed:57:2f:d2:cd:29:a3:5d
```

**Comment by aSemy** [comment]
Thanks, it looks promising.

Is there documentation on how to use it? I've had a look but it's not clear how to fetch data, or authenticate requests.

**Comment by averikitsch** [comment]
More instructions can be found https://github.com/googleapis/google-auth-library-java#using-credentials-with-google-http-client
