### ISSUE TITLE
SecretVersionName toString() not working

### ISSUE THREAD

**Issue by bashoogzaad** [googleapis/java-secretmanager#563]
I would like to destroy a SecretVersion and I follow the samples for this. However, this is not working. The error is as follows:

`Invalid character "/" in path section`

This seems to be triggered by the SecretVersionName toString() method, which builds the path, but without urlEncoding. And after that, the PathTemplate throws the error when the path contains a '/'.

This seems to be a bug in my opinion. I have solved it now to call SecretVersion getName() method and used that to destroy the version.

**Comment by lesv** [comment]
@sethvargo PTAL & comment

**Comment by sethvargo** [comment]
Hi @bashoogzaad can you please share the code you're using and the version of the library?

@lesv that code is all auto-generated.

**Comment by lesv** [comment]
Closing do to lack of response from customer
