### ISSUE TITLE
Upgrading from 2.0.4 to 2.0.5 causes the application to crash with a SIGSEGV in the JRE

### ISSUE THREAD

**Issue by lucaviolanti** [googleapis/java-secretmanager#651]
#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types: google-cloud-secretmanager 
2. OS type and version: Alpine Linux base docker image - eclipse-temurin:11-jre-alpine
3. Java version: OpenJDK Runtime Environment Temurin-11.0.13+8 (11.0.13+8) (build 11.0.13+8)
4. secretmanager version(s): 2.0.5

#### Steps to reproduce

  1. Upgrade from 2.0.4 to 2.0.5
  2. Application crashes with a segmentation fault in the JRE

#### Stack trace
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000003efe, pid=1, tid=36
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.13+8 (11.0.13+8) (build 11.0.13+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (11.0.13+8, mixed mode, tiered, compressed oops, serial gc, linux-amd64)
# Problematic frame:
# C  0x0000000000003efe
#
# Core dump will be written. Default location: /core.%e.1.%t
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```

**Comment by sethvargo** [comment]
Hey @lesv - I no longer work on Secret Manager. Sorry

**Comment by arjun-khadka** [comment]
Is there a temporary solution to this.

**Comment by lesv** [comment]
Any chance you can provide the code that your using to do this?  (without any PII)
Our samples still run, so we aren't seeing the problem you are having.

**Comment by arjun-khadka** [comment]
Changing the Dataproc image version for creating cluster to 2.0-debians from 1.5 solved my problem. This was used for spinning Spark cluster.

**Comment by lesv** [comment]
Sounds like the issue is solved.

**Comment by mplanchant** [comment]
Related to https://github.com/grpc/grpc-java/issues/8751
